/* AUTO-GENERATED by scripts/export-permissions.mjs — DO NOT EDIT.
 * functions/api/_permissions.js 가 이 모듈을 import (with 신문법 회피).
 */
/* eslint-disable */
export default {
  "generated_at": "2026-05-13T04:21:41.726Z",
  "version": "dev",
  "permissions": {
    "admin:user:set_admin": "owner",
    "admin:user:set_role": "owner",
    "admin:business:delete": "owner",
    "admin:user:delete": "owner",
    "admin:faq:write": "owner",
    "admin:error_log:clear_all": "owner",
    "admin:memo:bulk_delete": "owner",
    "admin:trash:purge": "owner",
    "admin:room:msg_bulk_delete": "owner",
    "admin:internal:read": "admin",
    "admin:user:approve": "admin",
    "admin:user:write": "admin",
    "admin:business:write": "admin",
    "admin:business:status": "admin",
    "admin:room:close": "admin",
    "admin:bulk_send": "admin",
    "admin:filing:approve": "admin",
    "customer:chat": "customer",
    "customer:upload_doc": "customer",
    "customer:mypage": "customer"
  }
};
